version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moviecut
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: run.py
      FLASK_ENV: production
      DATABASE_URL: postgresql://user:password@db:5432/moviecut
      TMDB_API_KEY: your_tmdb_api_key
    depends_on:
      - db

volumes:
  postgres_data: